worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: info

is-testing: false

server-port: 8080
server-grpc-port: 8081

secdist-path: /secure_data.json

dbconnection: 'postgresql://user_service_user:password@localhost:5432/user_service_db_1'
